[tools]
"aqua:casey/just" = "1.58.0"
"aqua:cli/cli" = "2.99.0"
"aqua:evilmartians/lefthook" = "2.1.12"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.53.6"
"go" = "1.27.1"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
]
